# Generated by Django 3.2.7 on 2021-09-20 07:18

from django.db import migrations
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shop.models.UserManager()),
            ],
        ),
    ]
